#!/usr/bin/env ruby

require 'webrick'
server = WEBrick::HTTPServer.new(Port: 3333)
server.mount_proc('/atom') { |req, res| res.body = '<!DOCTYPE html><html><head><link type="application/atom+xml" href="/atom.xml"></link></head><body>Hello, world!</body></html>' }
server.start
